POST http://localhost:8080/vitaChi/createBenutzerAccessoire
Content-Type: application/json

{"userID": 1, "accessoire": 3}

###
POST http://localhost:8080/vitaChi/createEingabe
Content-Type: application/json

{"eingabe":  {"bewertung1":  1, "bewertung2": 2, "typ": "Essen"}}

###
POST http://localhost:8080/vitaChi/createEingabe
Content-Type: application/json

{"eingabe":  {"bewertung1":  1, "bewertung2": 2, "typ": "Schlaf"}}

###
POST http://localhost:8080/vitaChi/createEingabe
Content-Type: application/json

{"eingabe":  {"bewertung1":  1, "bewertung2": 2, "typ": "Bewegung"}}

###
POST http://localhost:8080/vitaChi/createArbeit
Content-Type: application/json

{"arbeit":  {"start":  "2021-03-16 08:00:00.000000", "stop": "2021-03-16 12:00:00.000000"}}

###
GET http://localhost:8080/vitaChi/test/Aufgaben
###
GET http://localhost:8080/vitaChi/findAll/Eingabe
###
GET http://localhost:8080/vitaChi/find/Eingabe/1
###
DELETE http://localhost:8080/vitaChi/delete/Eingabe/1
###
POST http://localhost:8080/vitaChi/createEingabe
Content-Type: application/json

{
  "eingabe":
  {
  "bewertung1": "1",
  "bewertung2": "2",
  "typ": "1"
  }
}
###
GET http://localhost:8080/vitaChi/init
###
GET http://localhost:8080/vitaChi/getWohlbefinden
###
GET http://localhost:8080/vitaChi/getEssenAVG
###
GET http://localhost:8080/vitaChi/getBewegungAVG
###
GET http://localhost:8080/vitaChi/getSchlafAVG
###
GET http://localhost:8080/vitaChi/getWorkingTime
###
GET http://localhost:8080/vitaChi/getWokringPerWeek
###

