GET http://localhost:8080/vitaChi/test/Aufgaben
###
GET http://localhost:8080/vitaChi/init
###
GET http://localhost:8080/vitaChi/findAll/Eingabe
###
GET http://localhost:8080/vitaChi/find/Eingabe/1
###
DELETE http://localhost:8080/vitaChi/delete/Eingabe/1

POST http://localhost:8080/vitaChi/create
Content-Type: application/json
{
  "BEWERTUNG1": "1",
  "BEWERTUNG2": "2",
  "DATUM": "28.01.2003",
  "TYP": "1"
}
###
GET http://localhost:8080/vitaChi/getWohlbefinden
###
GET http://localhost:8080/vitaChi/getEssenAVG
###
GET http://localhost:8080/vitaChi/getBewegungAVG
###
GET http://localhost:8080/vitaChi/getSchlafAVG
